import axios from "axios";
import { AxiosResponse } from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useSetRecoilState } from "recoil";
import { Todo, todoAtom } from "./atom/todoAtom";

import TodoInput from "./TodoInput";
import TodoList from "./TodoList";

export const MOCK_TODOS_URL = "http://localhost:3001/todos/";

const Home: NextPage = () => {
    console.log("Home");
    const setTodoList = useSetRecoilState<Array<Todo>>(todoAtom);

    useEffect(() => {
        axios.get(MOCK_TODOS_URL).then((res: AxiosResponse<Array<Todo>>) => {
            setTodoList(res.data);
        });
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TodoInput />
            <TodoList />
        </div>
    );
};

export default Home;
