import type { NextPage } from "next";
import Head from "next/head";
import { RecoilRoot } from "recoil";

import TodoInput from "./TodoInput";
import TodoList from "./TodoList";

const Home: NextPage = () => {
    return (
        <RecoilRoot>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TodoInput />
            <TodoList />
        </RecoilRoot>
    );
};

export default Home;
