import React, { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import { useSetRecoilState } from "recoil";

import type { Todo } from "@prisma/client";

import { todoAtom } from "./atom/todoAtom";
import TodoInput from "./TodoInput";
import TodoList from "./TodoList";

const _Home: NextPage = () => {
    console.log("Home");
    const setTodoList = useSetRecoilState<Array<Todo>>(todoAtom);

    useEffect(() => {
        axios.get<Array<Todo>>("/api/todo",{
            headers: { "Content-Type": "application/json" },
        }).then((res) => {
            setTodoList(res.data);
        });
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <TodoInput />
            <TodoList />
        </div>
    );
};

const Home = React.memo(_Home);
export default Home;
